
development:
  dialect: mysql
  datasource: root:root@tcp(127.0.0.1:3306)/db_oauth?charset=utf8mb4&parseTime=true
  dir: db/migrations
  table: migrations

production:
  dialect: mysql
  datasource: root:root@tcp(127.0.0.1:3306)/db_oauth?charset=utf8mb4&parseTime=true
  dir: db/migrations
  table: migrations