version: '3.3'

services:
  db-oauth-go-server:
    container_name: db-oauth-go-server
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-oauth-server
    command: mysqld --innodb-buffer-pool-size=64M
    volumes:
      - db-oauth-server-go-data:/var/lib/mysql
    ports:
      - 13306:3306
    networks:
      - stack
networks: {stack: {}}
volumes:
  db-oauth-server-go-data: